name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3' # Sesuaikan dengan versi Go Anda

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Sesuaikan dengan versi Node.js Anda

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Remove node_modules after build
        run: rm -rf frontend/node_modules

      - name: Copy project to new directory on VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./"
          target: "~/go-face-auth-new"
          overwrite: true

      - name: Deploy and Restart on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Move to home directory for safety
            cd ~
            
            # Create a backup of the current deployment
            rm -rf go-face-auth-old
            if [ -d "go-face-auth" ]; then
              mv go-face-auth go-face-auth-old
            fi
            
            # Activate the new deployment
            mv go-face-auth-new go-face-auth
            
            # Enter the new project directory
            cd go-face-auth
            
            # Write .env file from GitHub Secret
            echo "${{ secrets.DOTENV_CONTENT }}" > .env
            
            # Build the Go backend
            echo "Building Go backend..."
            /usr/local/go/bin/go mod download
            /usr/local/go/bin/go build -o go-face-auth-server main.go
            
            # Restart the application service
            echo "Restarting application service..."
            sudo systemctl restart go-face-auth
            
            echo "Deployment successful!"