package models

import (
	"time"

	"gorm.io/gorm"
)

// CustomOffer represents a custom package offer generated by a superadmin for a specific company.
type CustomOffer struct {
	ID           uint           `gorm:"primaryKey" json:"id"`
	Token        string         `gorm:"unique;not null" json:"token"` // Unique token for the URL
	CompanyID    uint           `gorm:"not null" json:"company_id"`
	CompanyName  string         `gorm:"not null" json:"company_name"`
	PackageName  string         `gorm:"not null" json:"package_name"`
	MaxEmployees int            `gorm:"not null" json:"max_employees"`
	MaxLocations int            `gorm:"not null" json:"max_locations"`
	MaxShifts    int            `gorm:"not null" json:"max_shifts"`
	Features     string         `gorm:"type:text" json:"features"` // Comma-separated list of features
	FinalPrice   float64        `gorm:"not null" json:"final_price"`
	BillingCycle string         `gorm:"not null" json:"billing_cycle"` // e.g., "monthly", "yearly"
	Status       string         `gorm:"default:'pending'" json:"status"` // e.g., "pending", "accepted", "expired", "used"
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"index" json:"deleted_at,omitempty"`
}
